// Generated by CoffeeScript 1.10.0
(function() {
  var MazeController;

  MazeController = function() {
    this.canvas = null;
    this.context = null;
    this.maze = null;
    this.walker = null;
    this.algorithm = null;
    this.speed = null;
    return this;
  };

  MazeController.prototype.init = function(maze) {
    this.canvas = $('#imageView').get(0);
    this.context = this.canvas.getContext('2d');
    this.canvas.width = maze.width * Constant.SQUARE;
    this.canvas.height = maze.height * Constant.SQUARE;
    this.speed = maze.speed ? maze.speed : Constant.SPEED;
    this.maze = new MazeManager(this.context, maze);
    this.maze.draw();
    this.walker = new walkerManager(this.context, this.maze);
    this.walker.init();
    return this.algorithm = new Solver(this.walker);
  };

  MazeController.prototype.run = function() {
    if (!this.algorithm.isDone()) {
      this.algorithm.step();
      return window.mazeTimeout = window.setTimeout((function() {
        return controller.run();
      }), this.speed);
    } else {
      this.walker.maze.draw(true);
      return this.algorithm.solve();
    }
  };

  this.window.MazeController = MazeController;

}).call(this);

//# sourceMappingURL=controller.js.map
