// Generated by CoffeeScript 1.10.0
(function() {
  var controller;

  controller = new MazeController();

  $(document).ready(function() {
    controller.init(maze);
    return controller.run();
  });

  this.window.controller = controller;

}).call(this);

//# sourceMappingURL=init.js.map
