// Generated by CoffeeScript 1.10.0
(function() {
  var reset;

  reset = function() {
    var controller, height, width;
    if (window.mazeTimeout) {
      clearInterval(window.mazeTimeout);
    }
    controller = new MazeController();
    width = Math.floor(this.window.innerWidth / 2 / Constant.SQUARE) - 1;
    height = Math.floor(this.window.innerHeight / 2 / Constant.SQUARE) - 1;
    this.maze = this.generateMaze(width, height);
    this.window.controller = controller;
    controller.init(maze);
    return controller.run();
  };

  $(document).ready(function() {
    return reset();
  });

  $(window).resize(function() {
    return reset();
  });

  window.resetMaze = reset;

}).call(this);

//# sourceMappingURL=init.js.map
